name: Flutter Integration Test

on:
  pull_request:
    branches:
      - develop  # hoặc branch bạn muốn bảo vệ

permissions:
  contents: read
  pull-requests: write
jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Thiết lập Java (cần thiết cho build Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Cache Gradle dependencies

      # 3. Thiết lập Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0' # Thay bằng phiên bản Flutter bạn đang dùng
          channel: 'stable' # Hoặc 'beta', 'dev', 'master'
          cache: true # Cache Flutter dependencies

      # 4. Lấy dependencies của Flutter
      - name: Get Flutter dependencies
        run: flutter pub

      - name: Run Integration Tests
        run: flutter test test/app_test.dart > test_output.log || true

      - name: Read test result and comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const log = fs.readFileSync('test_output.log', 'utf8');
            const maxLen = 65000;
            const comment = log.length > maxLen ? log.slice(0, maxLen) + '\n\n... truncated ...' : log;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧪 **Flutter Integration Test Output**:\n\n\`\`\`\n${comment}\n\`\`\``
            });